### ISSUE TITLE
Exception JSONDecodeError

### ISSUE THREAD

**Issue by AndreyMrovol** [Prof-Bloodstone/Minecraft_scoreboard_exporter#1]
I got following error running mc_NBT_top_scores.py

`Exception JSONDecodeError occured. Trying again 2 more times.
Traceback (most recent call last):
  File "mc_NBT_top_scores.py", line 392, in main
    extract_and_save_data(args)
  File "mc_NBT_top_scores.py", line 240, in extract_and_save_data
    scores = get_scores(from_file, combine, sort, reverse, number, whitelist, blacklist, delete_combined)
  File "mc_NBT_top_scores.py", line 85, in get_scores
    objectives = extract_scores(file)
  File "mc_NBT_top_scores.py", line 45, in extract_scores
    for tag in nbtfile['data']['Objectives'].tags}
  File "mc_NBT_top_scores.py", line 45, in <dictcomp>
    for tag in nbtfile['data']['Objectives'].tags}
  File "D:\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by Prof-Bloodstone** [comment]
@AndreyMrovol How did you solve it?

My guess is that scoreboard file might have been  being modified when you ran that script.
